services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33061:3306"

  backend:
    build: ./backend
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: weatherdb
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8088:80"