services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33061:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 20
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: weatherdb
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: sh -c "sleep 15 && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8088:80"